#!/bin/sh
# Copyright (C) 2010  Tomohiro Matsuyama <tomo@cx4a.org>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


error() {
    echo "$1" >& 2
    exit 1
}

set $(grep 'VERSION =' $(dirname $0)/../bin/* | cut -d\' -f2 | sort -u)
case $# in
    0) error 'No version number found' ;;
    1) echo $1 ;;
    *) error "Unmatched version number:\n$*" ;;
esac
